version: "3.7"

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/home/node/app
  db:
    image: postgres:14.1
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: iducation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8SBwotk2lUX

volumes:
  postgres_data: